kind: pipeline
type: docker
name: release

trigger:
  ref:
    - refs/heads/trunk
    - refs/heads/stable
    - refs/tags/**

steps:
  - name: build
    image: 324181518966.dkr.ecr.us-west-2.amazonaws.com/debian-builder:54
    
    commands:
      - make upload-release

---
kind: pipeline
type: docker
name: daily-build

trigger:
  event:
    - cron
  cron:
    - daily-build

steps:
  - name: build
    image: 324181518966.dkr.ecr.us-west-2.amazonaws.com/debian-builder:54
    
    commands:
      - make upload-trunk
